[env]
TELEGRAM_BOT_TOKEN = "5938743745:AAH_vYTPnMWsol1fbtM_Ae5QOAe9Em-_qBw"

[build]
builder = "nixpacks"
buildCommand = "echo building!"

[deploy]
startCommand = "echo starting!"
restartPolicyType = "always"

[start]
web = "python bot.py"