[env]
TELEGRAM_BOT_TOKEN = "your-telegram-bot-token-here"

[build]
builder = "nixpacks"
buildCommand = "echo building!"

[deploy]
startCommand = "echo starting!"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"

[start]
web = "python bot.py"