[build]
builder = "nixpacks"
buildCommand = "echo building!"

[deploy]
startCommand = "echo starting!"
healthcheckPath = "/healthcheck"
healthcheckTimeout = 50
restartPolicyType = "never"

[healthcheck]
web = "/healthcheck"
